version: "3.9"

services:
  tmp_nest_graphql_server:
    container_name: tmp_nest_graphql_server
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    tty: true
    ports:
      - 3000:3000
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./backend:/backend
    depends_on:
      - tmp_nest_graphql_db
    # command: yarn start:dev

  tmp_nest_graphql_db:
    container_name: tmp_nest_graphql_db
    image: postgres:14
    restart: always
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ./db/postgres/data:/var/lib/postgresql/data
      - ./db/postgres/initdb:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - TZ=Asia/Tokyo

  tmp_nest_graphql_pgadmin:
    container_name: tmp_nest_graphql_pgadmin
    image: dpage/pgadmin4:4.2
    ports:
      - "8000:80"
    volumes:
      - ./db/pgadmin4:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD={PGADMIN_DEFAULT_PASSWORD}
    hostname: pgadmin4
    links:
      - tmp_nest_graphql_db
    restart: always

volumes:
  postgres:
    driver: local
