version: "3.9"

services:
  tmp_nest_graphql_server:
    container_name: tmp_nest_graphql_server
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    tty: true
    ports:
      - 3001:3000
    volumes:
      - ./backend:/backend
    command: yarn start:dev
